num_cores: 1
core_freq_mhz: 800
core_stats_print_period_cycles: 100000
num_systolic_array_per_core: 8

vpu_num_lanes: 32
vpu_spad_size_kb_per_lane: 256
vpu_vector_length_bits: 128

dram_type: ramulator2

dram_channels: 4
dram_stats_print_period_cycles: 100000
ramulator_config_path: ../configs/ramulator2_configs/LPDDR5X_9600.yaml

icnt_type: booksim2
icnt_freq_mhz: 800
icnt_injection_ports_per_core: 8
booksim_config_path: ../configs/booksim2_configs/fly_c8_m4.icnt

pytorchsim_functional_mode: 1
pytorchsim_timing_mode: 1

codegen_mapping_strategy: heuristic
codegen_external_mapping_file: ''
codegen_autotune_max_retry: 10
codegen_autotune_template_topk: 4
codegen_compiler_optimization: all
